spring:
  rabbitmq:
    host: 192.168.81.128
    port: 5672
    username: dengpan
    password: dp933632
zuul:
  routes:
    #自定义的路由规则名称
    myProduct:
      #要访问的服务名字
      serviceId: product
      #自定义的访问路径
      path: /myProduct/**
#    product: /myProduct/**
      #传递cookie
      sensitiveHeaders:
  ignored-patterns:
    - /**/product/listForOrder
    - /**/product/list

#暴露所有接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
