
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dp933632
    url: jdbc:mysql://127.0.0.1/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
      show-sql: true
#修改负载均衡的规则
PRODUCT: #服务名字
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #规则的全路径
girl:
  name: xiaowei233
  age: 22
