spring:
  application:
    name: product
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dp933632
    url: jdbc:mysql://127.0.0.1/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
